version: '3'
services:
    jenkins:
        image: jenkins
        volumes:
            - .:/var/jenkins_home/localdev
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
        ports:
            - "8080:8080"
            - "50000:50000"